### ISSUE TITLE
Build Error: BaSiC Plugin Download Failure in Docker Build Process

### ISSUE THREAD

**Issue by raisa-petrovic** [labsyspharm/basic-illumination#10]
Hi,
During the build process of the Docker image from the provided Dockerfile, an error occurs when attempting to download the BaSiC Plugin from https://www.helmholtz-muenchen.de/fileadmin/ICB/software/BaSiC/BaSiCPlugin.zip. The server responds with a 404 Not Found error, indicating that the file could not be found.
Can you help?
Best,
Raisa

**Comment by jmuhlich** [comment]
Sure. We need to update the URL in the Dockerfile to https://github.com/marrlab/BaSiC/raw/b6943502853c052fd93c6fabc807bc40907e73ce/BaSiCPlugin.zip .

**Comment by jmuhlich** [comment]
Fixed in d62aff4 and released in 1.3.0.
