### ISSUE TITLE
"ImageJ: command not found" on Galaxy

### ISSUE THREAD

**Issue by hengkp** [labsyspharm/basic-illumination#7]
Hi Developers,

I am first experiencing the Galaxy. I tried to run BaSiC Illumination in Galaxy, which was installed on macOS Monterey version 12.5. It showed an error as **".../tool_script.sh: line 26: ImageJ: command not found"**. Please kindly helps on this issue.

Thanks,
Heng

**Comment by alliecreason** [comment]
Hi Heng,

Could you tell us a bit more about your galaxy set up. Is this a local installation of galaxy? Has it been configured for running tools in conda environments or docker containers?

**Comment by hengkp** [comment]
Hi @alliecreason,

Thank you for your reply. I installed galaxy locally under the "/Users/heng/galaxy" directory. Also, conda and docker are available in the base environment (the version shown below).

<img width="697" alt="Screen Shot 2565-07-30 at 09 29 39" src="https://user-images.githubusercontent.com/40425349/181866761-becfcec0-525b-4a64-887b-92b5264f55bd.png">

Apart from the installation of galaxy followed by  [this page](https://galaxyproject.org/admin/get-galaxy/), I have only set an admin user and installed tools in the galaxy. It might not be configured either conda or docker yet. So, which one should I select to run your workflow perfectly?

Thanks,
Heng

**Comment by hengkp** [comment]
Hi @Xujingkk ,

Unfortunately, I did not solve this problem. I have been moving to the [MCMICRO](https://mcmicro.org) which contains the BaSiC package as an optional tool according to the reference [here](https://mcmicro.org/io.html#optional-illumination-corrected-images). There is also a Galaxy version that you can try, but I recommend using the command's version.

Hope this helps,
Heng

**Comment by hengkp** [comment]
Hi @Xujingkk ,

Unfortunately, I did not solve this problem. I have been moving to the [MCMICRO](https://mcmicro.org) which contains the BaSiC package as an optional tool according to the reference [here](https://mcmicro.org/io.html#optional-illumination-corrected-images). There is also a Galaxy version that you can try, but I recommend using the command's version.

Hope this helps,
Heng
